---
ruby_version: '3.4.7'
ruby_prefix_base: '/opt/ruby'
ruby_prefix: '{{ ruby_prefix_base }}/{{ ruby_version }}'

postgres_superuser_password: 'QCT@Admin'

redmine_version: '6.1.0'
redmine_root_base: '/opt/redmine'
redmine_root: '{{ redmine_root_base }}/{{ redmine_version }}'
redmine_user: 'redmine'
redmine_group: 'redmine'
redmine_default_lang: 'en'

redmine_db_name: 'redmine'
redmine_db_user: 'redmine'
redmine_db_password: 'QCT@Admin'
redmine_db_host: '127.0.0.1'
redmine_db_port: 5432

redis_version: '8.4.0'
redis_prefix: '/opt/redis/{{ redis_version }}'
redis_src_dir: '/usr/local/src'
redis_user: 'redis'
redis_group: 'redis'
redis_conf_dir: '/etc/redis'
redis_data_dir: '/var/lib/redis'
redis_bind_address: '127.0.0.1'
redis_port: 6379
