---
- hosts: redmine_servers
  become: true

  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'ruby', tags: 'ruby' }
    - { role: 'postgres', tags: 'postgres' }
    - { role: 'redmine', tags: 'redmine' }
    - { role: 'puma', tags: 'puma' }
    - { role: 'nginx', tags: 'nginx' }
    - { role: 'selinux', tags: 'selinux' }
